export const FIREBASE_ERROR_MAP: Record<string, string> = {
  'auth/too-many-requests': 'firebase.tooManyRequests',
  'auth/claims-too-large': 'firebase.claimsTooLarge',
  'auth/email-already-exists': 'firebase.emailExists',
  'auth/user-not-found': 'firebase.userNotFound',
  'auth/wrong-password': 'firebase.wrongPassword',
  'auth/email-already-in-use': 'firebase.emailAlreadyInUse',
  'auth/insufficient-permission': 'firebase.insufficientPermission',
  'auth/internal-error': 'firebase.internalError',
  'auth/invalid-argument': 'firebase.invalidArgument',
  'auth/invalid-claims': 'firebase.invalidClaims',
  'auth/invalid-continue-uri': 'firebase.invalidContinueUri',
  'auth/invalid-creation-time': 'firebase.invalidCreationTime',
  'auth/invalid-credential': 'firebase.invalidCredential',
  'auth/invalid-disabled-field': 'firebase.invalidDisabledField',
  'auth/invalid-display-name': 'firebase.invalidDisplayName',
  'auth/invalid-dynamic-link-domain': 'firebase.invalidDynamicLinkDomain',
  'auth/invalid-email': 'firebase.invalidEmail',
  'auth/invalid-email-verified': 'firebase.invalidEmailVerified',
  'auth/invalid-hash-algorithm': 'firebase.invalidHashAlgorithm',
  'auth/invalid-hash-block-size': 'firebase.invalidHashBlockSize',
  'auth/invalid-hash-derived-key-length':
    'firebase.invalidHashDerivedKeyLength',
  'auth/invalid-hash-key': 'firebase.invalidHashKey',
  'auth/invalid-hash-memory-cost': 'firebase.invalidHashMemoryCost',
  'auth/invalid-hash-parallelization': 'firebase.invalidHashParallelization',
  'auth/invalid-hash-rounds': 'firebase.invalidHashRounds',
  'auth/invalid-hash-salt-separator': 'firebase.invalidHashSaltSeparator',
  'auth/invalid-id-token': 'firebase.invalidIdToken',
  'auth/invalid-last-sign-in-time': 'firebase.invalidLastSignInTime',
  'auth/invalid-page-token': 'firebase.invalidPageToken',
  'auth/invalid-password': 'firebase.invalidPassword',
  'auth/invalid-password-has': 'firebase.invalidPasswordHash',
  'auth/invalid-password-salt': 'firebase.invalidPasswordSalt',
  'auth/invalid-phone-number': 'firebase.invalidPhoneNumber',
  'auth/invalid-photo-url': 'firebase.invalidPhotoUrl',
  'auth/invalid-provider-data': 'firebase.invalidProviderData',
  'auth/invalid-provider-id': 'firebase.invalidProviderId',
  'auth/invalid-oauth-responsetype': 'firebase.invalidOauthResponseType',
  'auth/invalid-session-cookie-duration':
    'firebase.invalidSessionCookieDuration',
  'auth/invalid-uid': 'firebase.invalidUid',
  'auth/invalid-user-import': 'firebase.invalidUserImport',
  'auth/maximum-user-count-exceeded': 'firebase.maximumUserCountExceeded',
  'auth/missing-android-pkg-name': 'firebase.missingAndroidPkgName',
  'auth/missing-continue-uri': 'firebase.missingContinueUri',
  'auth/missing-hash-algorithm': 'firebase.missingHashAlgorithm',
  'auth/missing-ios-bundle-id': 'firebase.missingIosBundleId',
  'auth/missing-uid': 'firebase.missingUid',
  'auth/missing-oauth-client-secret': 'firebase.missingOauthClientSecret',
  'auth/operation-not-allowed': 'firebase.operationNotAllowed',
  'auth/phone-number-already-exists': 'firebase.phoneNumberExists',
  'auth/project-not-found': 'firebase.projectNotFound',
  'auth/reserved-claims': 'firebase.reservedClaims',
  'auth/session-cookie-expired': 'firebase.sessionCookieExpired',
  'auth/session-cookie-revoked': 'firebase.sessionCookieRevoked',
  'auth/uid-already-exists': 'firebase.uidExists',
  'auth/unauthorized-continue-uri': 'firebase.unauthorizedContinueUri',
  'auth/network-request-failed': 'firebase.networkFailed',
  'auth/developer-error': 'firebase.developerError',
};
