export const FontFamily = {
  InterTightBlack: 'InterTight-Black',
  InterTightBlackItalic: 'InterTight-BlackItalic',
  InterTightBold: 'InterTight-Bold',
  InterTightBoldItalic: 'InterTight-BoldItalic',
  InterTightExtraBold: 'InterTight-ExtraBold',
  InterTightExtraBoldItalic: 'InterTight-ExtraBoldItalic',
  InterTightExtraLight: 'InterTight-ExtraLight',
  InterTightExtraLightItalic: 'InterTight-ExtraLightItalic',
  InterTightItalic: 'InterTight-Italic',
  InterTightLight: 'InterTight-Light',
  InterTightLightItalic: 'InterTight-LightItalic',
  InterTightMedium: 'InterTight-Medium',
  InterTightMediumItalic: 'InterTight-MediumItalic',
  InterTightRegular: 'InterTight-Regular',
  InterTightSemiBold: 'InterTight-SemiBold',
  InterTightSemiBoldItalic: 'InterTight-SemiBoldItalic',
  InterTightThin: 'InterTight-Thin',
  InterTightThinItalic: 'InterTight-ThinItalic',
} as const;
